# Generated by Django 5.2.14 on 2026-05-26 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('dnd_options', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('build_type', models.CharField(choices=[('PLAYER_CHARACTER', 'Player Character'), ('NPC', 'NPC')], default='PLAYER_CHARACTER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('CAMPAIGN_VISIBLE', 'Campaign Visible')], default='PRIVATE', max_length=20)),
                ('character_level', models.PositiveIntegerField(default=1)),
                ('ability_scores', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('manual_overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacks_actions', models.ManyToManyField(blank=True, related_name='attack_builds', to='dnd_options.dndoption')),
                ('background_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_builds', to='dnd_options.dndoption')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_builds', to='campaigns.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_builds', to=settings.AUTH_USER_MODEL)),
                ('selected_equipment', models.ManyToManyField(blank=True, related_name='equipment_builds', to='dnd_options.dndoption')),
                ('selected_feats', models.ManyToManyField(blank=True, related_name='feat_builds', to='dnd_options.dndoption')),
                ('selected_features', models.ManyToManyField(blank=True, related_name='feature_builds', to='dnd_options.dndoption')),
                ('selected_spells', models.ManyToManyField(blank=True, related_name='spell_builds', to='dnd_options.dndoption')),
                ('species_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_builds', to='dnd_options.dndoption')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_count', models.PositiveIntegerField(default=1)),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('character_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='characters.characterbuild')),
                ('class_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_level_entries', to='dnd_options.dndoption')),
                ('subclass_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclass_level_entries', to='dnd_options.dndoption')),
            ],
            options={
                'ordering': ['ordering'],
                'unique_together': {('character_build', 'ordering')},
            },
        ),
    ]
