# Generated by Django 5.2.14 on 2026-06-05 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        (
            "dnd_options",
            "0002_dndoption_build_notes_dndoption_mechanical_tags_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="characterbuild",
            name="last_validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characterbuild",
            name="needs_revalidation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="characterbuild",
            name="revalidation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="characterclasslevel",
            name="selected_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characterbuild",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("VALID", "Valid"),
                    ("INVALID", "Invalid"),
                    ("STALE", "Stale"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CharacterSelectedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("SPECIES", "Species"),
                            ("BACKGROUND", "Background"),
                            ("FEAT", "Feat"),
                            ("SPELL", "Spell"),
                            ("EQUIPMENT", "Equipment"),
                            ("FEATURE", "Feature"),
                            ("ATTACK", "Attack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="characters.characterbuild",
                    ),
                ),
                (
                    "dnd_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_selected_entries",
                        to="dnd_options.dndoption",
                    ),
                ),
            ],
            options={
                "ordering": ["selected_at"],
                "unique_together": {("character_build", "dnd_option", "option_type")},
            },
        ),
    ]
