# Generated by Django 5.2.14 on 2026-05-26 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNDOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('option_type', models.CharField(choices=[('CLASS', 'Class'), ('SUBCLASS', 'Subclass'), ('SPECIES', 'Species/Race/Lineage'), ('BACKGROUND', 'Background'), ('FEAT', 'Feat'), ('SPELL', 'Spell'), ('EQUIPMENT', 'Equipment'), ('FEATURE', 'Feature/Trait'), ('ATTACK', 'Attack/Action'), ('FIGHTING_STYLE', 'Fighting Style'), ('INVOCATION', 'Invocation'), ('MANEUVER', 'Maneuver'), ('OTHER', 'Other')], max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('source_category', models.CharField(choices=[('official', 'Official'), ('setting-specific', 'Setting Specific'), ('unearthed-arcana', 'Unearthed Arcana'), ('homebrew', 'Homebrew'), ('custom', 'Custom')], default='official', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('prerequisites', models.JSONField(blank=True, default=dict)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_options', to='dnd_options.dndoption')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
