# Generated by Django 5.2.14 on 2026-06-03 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_options", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dndoption",
            name="build_notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="mechanical_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="primary_ability_scores",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="review_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("NEEDS_REVIEW", "Needs Review"),
                    ("IN_REVIEW", "In Review"),
                    ("REVIEWED", "Reviewed"),
                ],
                default="CLEAN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_dnd_options",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dndoption",
            name="visual_or_flavor_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="dndoption",
            name="traits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="DNDOptionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In Review"),
                            ("CHANGES_REQUESTED", "Changes Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NO_CHANGE_NEEDED", "No Change Needed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("ai_review_reasons", models.JSONField(blank=True, default=list)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_dnd_option_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dnd_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="dnd_options.dndoption",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_dnd_option_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_dnd_option_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DNDOptionReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "target_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("target_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("DM_ONLY", "DM Only"),
                            ("ADMIN_ONLY", "Admin Only"),
                        ],
                        default="PUBLIC",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dnd_option_review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="dnd_options.dndoptionreview",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DNDOptionSuggestedChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_path", models.CharField(max_length=255)),
                ("current_value", models.JSONField(blank=True, null=True)),
                ("proposed_value", models.JSONField(blank=True, null=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("REPLACE", "Replace"),
                            ("ADD", "Add"),
                            ("REMOVE", "Remove"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_dnd_option_suggested_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dnd_option_suggested_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_changes",
                        to="dnd_options.dndoptionreview",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_dnd_option_suggested_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
