ALLOWED_TRAITS = [
    # movement
    "teleportation",
    "flight",
    "climbing",
    "swimming",
    "burrowing",
    "increased speed",
    "mobility",
    "mounted combat",
    "forced movement",
    "push",
    "pull",
    "knock prone",
    "difficult terrain",
    "terrain traversal",
    "initiative bonus",
    "ambush",
    "escape",

    # combat style
    "melee",
    "ranged",
    "unarmed",
    "natural weapons",
    "duelist",
    "two weapon fighting",
    "archery",
    "thrown weapons",
    "heavy weapon",
    "reach weapon",
    "finesse weapon",
    "shield",
    "defensive fighting",
    "offensive fighting",
    "hit and run",
    "grappling",
    "shoving",
    "opportunity attacks",
    "extra attack",
    "bonus action attacks",
    "reaction attacks",
    "critical hits",
    "sneak attack",
    "smite",
    "maneuvers",
    "melee spellcaster",

    # role
    "striker",
    "tank",
    "support",
    "healer",
    "controller",
    "defender",
    "scout",
    "face",
    "skill expertise",
    "summoner",
    "blaster",
    "battlefield commander",
    "protector",
    "infiltrator",
    "assassin",
    "anti-mage",
    "single target damage",
    "area damage",
    "nova damage",
    "sustained damage",
    "battlefield control",
    "social manipulation",
    "exploration",
    "survivalist",
    "utility caster",

    # armor / durability
    "high armor class",
    "light armor",
    "medium armor",
    "heavy armor",
    "unarmored defense",
    "damage resistance",
    "damage immunity",
    "condition immunity",
    "temporary hit points",
    "self healing",
    "damage reduction",
    "saving throw bonus",
    "evasion",
    "uncanny dodge",
    "death prevention",
    "revival",
    "regeneration",
    "warding",
    "aura",
    "protect allies",
    "redirect damage",
    "retaliation damage",

    # magic style / class resources
    "spellcasting",
    "full caster",
    "half caster",
    "third caster",
    "arcane",
    "divine",
    "primal",
    "pact magic",
    "prepared casting",
    "known spells",
    "ritual casting",
    "cantrips",
    "ki",
    "rage",
    "wild shape",
    "bardic inspiration",
    "channel divinity",
    "metamagic",
    "eldritch invocations",
    "artificer infusions",
    "superiority dice",
    "sorcery points",
    "lay on hands",
    "pact boon",
    "companion feature",

    # spell method / magical effect
    "abjuration",
    "conjuration",
    "divination",
    "enchantment",
    "evocation",
    "illusion",
    "necromancy",
    "transmutation",
    "summoning",
    "healing",
    "buffing",
    "debuffing",
    "charm",
    "fear",
    "mind control",
    "counterspell",
    "dispel magic",
    "curse",
    "blessing",
    "telepathy",
    "telekinesis",
    "shapechanging",
    "familiar",
    "pet",

    # damage / element theme
    "acid",
    "bludgeoning",
    "cold",
    "fire",
    "force",
    "lightning",
    "necrotic",
    "piercing",
    "poison",
    "psychic",
    "radiant",
    "slashing",
    "thunder",

    # conditions / status effects
    "blinded",
    "charmed",
    "deafened",
    "frightened",
    "grappled",
    "incapacitated",
    "invisible",
    "paralyzed",
    "petrified",
    "poisoned",
    "prone",
    "restrained",
    "stunned",
    "unconscious",
    "exhaustion",
    "silence",

    # creature / supernatural theme
    "aberration",
    "beast",
    "celestial",
    "construct",
    "dragon",
    "elemental",
    "fey",
    "fiend",
    "giant",
    "monstrosity",
    "plant",
    "undead",
    "spirit",
    "ghost",
    "shadow",
    "darkness",
    "light",
    "holy",
    "fiendish",
    "eldritch",
    "cosmic",
    "nature",
    "storm",
    "sea",
    "plague",
    "death",
    "life",

    # class fantasy / flavor
    "warrior",
    "scholar",
    "criminal",
    "religious",
    "priest",
    "oracle",
    "shaman",
    "witch",
    "knight",
    "samurai",
    "gladiator",
    "soldier",
    "mercenary",
    "thief",
    "spy",
    "pirate",
    "swashbuckler",
    "hunter",
    "ranger",
    "warden",
    "guardian",
    "music",
    "performance",
    "storytelling",
    "alchemy",
    "technology",
    "rune magic",
    "echo magic",
    "time magic",
    "gravity magic",
    "blood magic",
    "shadow magic",
    "clockwork",
    "order",
    "peace",
    "twilight",
    "forge",
    "grave",
    "war",
    "knowledge",
    "trickery",
    "vengeance",
    "devotion",
    "redemption",
    "conquest",
    "glory",
    "watchers",
    "ancients",

    # abilities
    "strength",
    "dexterity",
    "constitution",
    "intelligence",
    "wisdom",
    "charisma",

    # saving throws
    "strength saves",
    "dexterity saves",
    "constitution saves",
    "intelligence saves",
    "wisdom saves",
    "charisma saves",
    "death saves",
    "concentration saves",

    # skills
    "stealth",
    "acrobatics",
    "athletics",
    "perception",
    "persuasion",
    "deception",
    "intimidation",
    "performance",
    "survival",
    "investigation",
    "religion",
    "arcana",
    "medicine",
    "animal handling",
    "history",
    "insight",
    "nature",
    "sleight of hand",
    "expertise",
    "jack of all trades",
    "reliable talent",

    # tools / proficiencies
    "thieves tools",
    "artisan tools",
    "musical instruments",
    "gaming sets",
    "vehicles",
    "disguise kit",
    "forgery kit",
    "poisoner's kit",
    "herbalism kit",
    "navigator's tools",
    "smith's tools",
    "alchemist's supplies",
    "tinker's tools",
    "brewer's supplies",
    "cook's utensils",
    "cartographer's tools",
    "calligrapher's supplies",
    "woodcarver's tools",
    "leatherworker's tools",
    "mason's tools",
    "painter's supplies",
    "potter's tools",
    "weaver's tools",
    "jeweler's tools",

    # utility / exploration / downtime
    "crafting",
    "magic item crafting",
    "scrolls",
    "potions",
    "traps",
    "locks",
    "language utility",
    "downtime utility",
    "disguise",
    "impersonation",
    "leadership",
    "negotiation",
    "nobility",
    "criminal contacts",
    "religious authority",
    "military authority",
    "academic knowledge",

    # resource cadence / action economy
    "short rest recovery",
    "long rest recovery",
    "limited use feature",
    "at will feature",
    "resource pool",
    "once per turn",
    "once per round",
    "concentration",
    "bonus action",
    "reaction",
    "action economy",

    # character advancement / feat mechanics
    "ability score increase",
    "feat prerequisite",
    "racial prerequisite",
    "species prerequisite",
    "class prerequisite",
    "spellcasting prerequisite",
    "proficiency prerequisite",

    # spell / magic mechanics
    "spell slots",
    "innate spellcasting",
    "lineage spellcasting",
    "spell choice",
    "spell save dc",
    "spell attack bonus",
    "component-free casting",
    "material component",
    "verbal component",
    "somatic component",

    # resource / recovery / usage
    "proficiency bonus uses",
    "ability modifier uses",
    "hit dice",
    "hit point maximum reduction",
    "random effect",
    "dm optional feature",
    "optional rule",
    "campaign specific",

    # defenses / survivability
    "advantage",
    "disadvantage",
    "immunity",
    "resistance",
    "condition resistance",

    # combat mechanics
    "weapon proficiency",
    "armor proficiency",
    "shield proficiency",
    "damage reroll",
    "bonus damage",
    "called shot",
    "weapon mastery",

    # senses / perception
    "darkvision",
    "blindsight",
    "tremorsense",
    "truesight",
    "passive perception",

    # social / utility
    "languages",
    "telepathic communication",
    "reading lips",
    "memory",
    "tracking",
    "foraging",

    # healing / rest
    "healing dice",
    "stabilization",
    "rest improvement",

    # item / equipment interaction
    "magic item use",
    "attunement",
    "equipment proficiency"
]
