CLASS_LIST = {
    'Artificer': {
        'source_url': 'https://dnd5e.wikidot.com/artificer',
        'subclasses': [
            ('Alchemist', 'https://dnd5e.wikidot.com/artificer:alchemist'),
            ('Armorer', 'https://dnd5e.wikidot.com/artificer:armorer'),
            ('Artillerist', 'https://dnd5e.wikidot.com/artificer:artillerist'),
            ('Battle Smith', 'https://dnd5e.wikidot.com/artificer:battle-smith'),
        ],
    },
    'Barbarian': {
        'source_url': 'https://dnd5e.wikidot.com/barbarian',
        'subclasses': [
            ('Path of the Ancestral Guardian',
             'https://dnd5e.wikidot.com/barbarian:ancestral-guardian'),
            ('Path of the Battlerager',
             'https://dnd5e.wikidot.com/barbarian:battlerager'),
            ('Path of the Beast', 'https://dnd5e.wikidot.com/barbarian:beast'),
            ('Path of the Berserker', 'https://dnd5e.wikidot.com/barbarian:berserker'),
            ('Path of the Giant', 'https://dnd5e.wikidot.com/barbarian:giant'),
            ('Path of the Storm Herald',
             'https://dnd5e.wikidot.com/barbarian:storm-herald'),
            ('Path of the Totem Warrior',
             'https://dnd5e.wikidot.com/barbarian:totem-warrior'),
            ('Path of Wild Magic', 'https://dnd5e.wikidot.com/barbarian:wild-magic'),
            ('Path of the Zealot', 'https://dnd5e.wikidot.com/barbarian:zealot'),
        ],
    },
    'Bard': {
        'source_url': 'https://dnd5e.wikidot.com/bard',
        'subclasses': [
            ('College of Creation', 'https://dnd5e.wikidot.com/bard:creation'),
            ('College of Eloquence', 'https://dnd5e.wikidot.com/bard:eloquence'),
            ('College of Glamour', 'https://dnd5e.wikidot.com/bard:glamour'),
            ('College of Lore', 'https://dnd5e.wikidot.com/bard:lore'),
            ('College of Spirits', 'https://dnd5e.wikidot.com/bard:spirits'),
            ('College of Swords', 'https://dnd5e.wikidot.com/bard:swords'),
            ('College of Valor', 'https://dnd5e.wikidot.com/bard:valor'),
            ('College of Whispers', 'https://dnd5e.wikidot.com/bard:whispers'),
        ],
    },
    'Cleric': {
        'source_url': 'https://dnd5e.wikidot.com/cleric',
        'subclasses': [
            ('Arcana Domain', 'https://dnd5e.wikidot.com/cleric:arcana'),
            ('Death Domain', 'https://dnd5e.wikidot.com/cleric:death'),
            ('Forge Domain', 'https://dnd5e.wikidot.com/cleric:forge'),
            ('Grave Domain', 'https://dnd5e.wikidot.com/cleric:grave'),
            ('Knowledge Domain', 'https://dnd5e.wikidot.com/cleric:knowledge'),
            ('Life Domain', 'https://dnd5e.wikidot.com/cleric:life'),
            ('Light Domain', 'https://dnd5e.wikidot.com/cleric:light'),
            ('Nature Domain', 'https://dnd5e.wikidot.com/cleric:nature'),
            ('Order Domain', 'https://dnd5e.wikidot.com/cleric:order'),
            ('Peace Domain', 'https://dnd5e.wikidot.com/cleric:peace'),
            ('Tempest Domain', 'https://dnd5e.wikidot.com/cleric:tempest'),
            ('Trickery Domain', 'https://dnd5e.wikidot.com/cleric:trickery'),
            ('Twilight Domain', 'https://dnd5e.wikidot.com/cleric:twilight'),
            ('War Domain', 'https://dnd5e.wikidot.com/cleric:war'),
        ],
    },
    'Druid': {
        'source_url': 'https://dnd5e.wikidot.com/druid',
        'subclasses': [
            ('Circle of Dreams', 'https://dnd5e.wikidot.com/druid:dreams'),
            ('Circle of the Land', 'https://dnd5e.wikidot.com/druid:land'),
            ('Circle of the Moon', 'https://dnd5e.wikidot.com/druid:moon'),
            ('Circle of the Shepherd', 'https://dnd5e.wikidot.com/druid:shepherd'),
            ('Circle of Spores', 'https://dnd5e.wikidot.com/druid:spores'),
            ('Circle of Stars', 'https://dnd5e.wikidot.com/druid:stars'),
            ('Circle of Wildfire', 'https://dnd5e.wikidot.com/druid:wildfire'),
        ],
    },
    'Fighter': {
        'source_url': 'https://dnd5e.wikidot.com/fighter',
        'subclasses': [
            ('Arcane Archer', 'https://dnd5e.wikidot.com/fighter:arcane-archer'),
            ('Banneret', 'https://dnd5e.wikidot.com/fighter:banneret'),
            ('Battle Master', 'https://dnd5e.wikidot.com/fighter:battle-master'),
            ('Cavalier', 'https://dnd5e.wikidot.com/fighter:cavalier'),
            ('Champion', 'https://dnd5e.wikidot.com/fighter:champion'),
            ('Echo Knight', 'https://dnd5e.wikidot.com/fighter:echo-knight'),
            ('Eldritch Knight', 'https://dnd5e.wikidot.com/fighter:eldritch-knight'),
            ('Psi Warrior', 'https://dnd5e.wikidot.com/fighter:psi-warrior'),
            ('Rune Knight', 'https://dnd5e.wikidot.com/fighter:rune-knight'),
            ('Samurai', 'https://dnd5e.wikidot.com/fighter:samurai'),
        ],
    },
    'Monk': {
        'source_url': 'https://dnd5e.wikidot.com/monk',
        'subclasses': [
            ('Way of Mercy', 'https://dnd5e.wikidot.com/monk:mercy'),
            ('Way of the Ascendant Dragon',
             'https://dnd5e.wikidot.com/monk:ascendant-dragon'),
            ('Way of the Astral Self', 'https://dnd5e.wikidot.com/monk:astral-self'),
            ('Way of the Drunken Master',
             'https://dnd5e.wikidot.com/monk:drunken-master'),
            ('Way of the Four Elements',
             'https://dnd5e.wikidot.com/monk:four-elements'),
            ('Way of the Kensei', 'https://dnd5e.wikidot.com/monk:kensei'),
            ('Way of the Long Death', 'https://dnd5e.wikidot.com/monk:long-death'),
            ('Way of the Open Hand', 'https://dnd5e.wikidot.com/monk:open-hand'),
            ('Way of Shadow', 'https://dnd5e.wikidot.com/monk:shadow'),
            ('Way of the Sun Soul', 'https://dnd5e.wikidot.com/monk:sun-soul'),
        ],
    },
    'Paladin': {
        'source_url': 'https://dnd5e.wikidot.com/paladin',
        'subclasses': [
            ('Oath of the Ancients', 'https://dnd5e.wikidot.com/paladin:ancients'),
            ('Oath of Conquest', 'https://dnd5e.wikidot.com/paladin:conquest'),
            ('Oath of the Crown', 'https://dnd5e.wikidot.com/paladin:crown'),
            ('Oath of Devotion', 'https://dnd5e.wikidot.com/paladin:devotion'),
            ('Oath of Glory', 'https://dnd5e.wikidot.com/paladin:glory'),
            ('Oath of Redemption', 'https://dnd5e.wikidot.com/paladin:redemption'),
            ('Oath of Vengeance', 'https://dnd5e.wikidot.com/paladin:vengeance'),
            ('Oath of the Watchers', 'https://dnd5e.wikidot.com/paladin:watchers'),
            ('Oathbreaker', 'https://dnd5e.wikidot.com/paladin:oathbreaker'),
        ],
    },
    'Ranger': {
        'source_url': 'https://dnd5e.wikidot.com/ranger',
        'subclasses': [
            ('Beast Master Conclave', 'https://dnd5e.wikidot.com/ranger:beast-master'),
            ('Drakewarden', 'https://dnd5e.wikidot.com/ranger:drakewarden'),
            ('Fey Wanderer', 'https://dnd5e.wikidot.com/ranger:fey-wanderer'),
            ('Gloom Stalker Conclave', 'https://dnd5e.wikidot.com/ranger:gloom-stalker'),
            ('Horizon Walker Conclave',
             'https://dnd5e.wikidot.com/ranger:horizon-walker'),
            ('Hunter Conclave', 'https://dnd5e.wikidot.com/ranger:hunter'),
            ('Monster Slayer Conclave',
             'https://dnd5e.wikidot.com/ranger:monster-slayer'),
            ('Swarmkeeper', 'https://dnd5e.wikidot.com/ranger:swarmkeeper'),
        ],
    },
    'Rogue': {
        'source_url': 'https://dnd5e.wikidot.com/rogue',
        'subclasses': [
            ('Arcane Trickster', 'https://dnd5e.wikidot.com/rogue:arcane-trickster'),
            ('Assassin', 'https://dnd5e.wikidot.com/rogue:assassin'),
            ('Inquisitive', 'https://dnd5e.wikidot.com/rogue:inquisitive'),
            ('Mastermind', 'https://dnd5e.wikidot.com/rogue:mastermind'),
            ('Phantom', 'https://dnd5e.wikidot.com/rogue:phantom'),
            ('Scout', 'https://dnd5e.wikidot.com/rogue:scout'),
            ('Soulknife', 'https://dnd5e.wikidot.com/rogue:soulknife'),
            ('Swashbuckler', 'https://dnd5e.wikidot.com/rogue:swashbuckler'),
            ('Thief', 'https://dnd5e.wikidot.com/rogue:thief'),
        ],
    },
    'Sorcerer': {
        'source_url': 'https://dnd5e.wikidot.com/sorcerer',
        'subclasses': [
            ('Aberrant Mind', 'https://dnd5e.wikidot.com/sorcerer:aberrant-mind'),
            ('Clockwork Soul', 'https://dnd5e.wikidot.com/sorcerer:clockwork-soul'),
            ('Draconic Bloodline', 'https://dnd5e.wikidot.com/sorcerer:draconic-bloodline'),
            ('Divine Soul', 'https://dnd5e.wikidot.com/sorcerer:divine-soul'),
            ('Lunar Sorcery', 'https://dnd5e.wikidot.com/sorcerer:lunar-sorcery'),
            ('Shadow Magic', 'https://dnd5e.wikidot.com/sorcerer:shadow-magic'),
            ('Storm Sorcery', 'https://dnd5e.wikidot.com/sorcerer:storm-sorcery'),
            ('Wild Magic', 'https://dnd5e.wikidot.com/sorcerer:wild-magic'),
        ],
    },
    'Warlock': {
        'source_url': 'https://dnd5e.wikidot.com/warlock',
        'subclasses': [
            ('Archfey', 'https://dnd5e.wikidot.com/warlock:archfey'),
            ('Celestial', 'https://dnd5e.wikidot.com/warlock:celestial'),
            ('Fathomless', 'https://dnd5e.wikidot.com/warlock:fathomless'),
            ('Fiend', 'https://dnd5e.wikidot.com/warlock:fiend'),
            ('The Genie', 'https://dnd5e.wikidot.com/warlock:genie'),
            ('Great Old One', 'https://dnd5e.wikidot.com/warlock:great-old-one'),
            ('Hexblade', 'https://dnd5e.wikidot.com/warlock:hexblade'),
            ('Undead', 'https://dnd5e.wikidot.com/warlock:undead'),
            ('Undying', 'https://dnd5e.wikidot.com/warlock:undying'),
        ],
    },
    'Wizard': {
        'source_url': 'https://dnd5e.wikidot.com/wizard',
        'subclasses': [
            ('Wizard Core', 'https://dnd5e.wikidot.com/spells:wizard-core'),
        ],
    },
}
