# Generated by Django 5.2.14 on 2026-05-26 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0001_initial'),
        ('dnd_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_character_level', models.PositiveIntegerField(default=1)),
                ('starting_gold_formula', models.CharField(default='0', max_length=255)),
                ('allowed_source_categories', models.JSONField(blank=True, default=list)),
                ('allow_multiclassing', models.BooleanField(default=True)),
                ('allow_feats', models.BooleanField(default=True)),
                ('hidden_ai_guidance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RulesetBannedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned_character_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruleset_bans', to='characters.characterbuild')),
                ('banned_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruleset_bans', to='dnd_options.dndoption')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_options', to='rulesets.ruleset')),
            ],
        ),
    ]
