# Generated by Django 5.2.14 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulesets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='banned_classes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='banned_feats',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='banned_species',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='banned_spells',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='banned_subclasses',
            field=models.JSONField(default=list),
        ),
    ]
