# Generated by Django 5.2.14 on 2026-06-08 14:07

import rulesets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rulesets", "0002_ruleset_banned_lists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleset",
            name="starting_gold_formula",
            field=models.CharField(
                default="0",
                max_length=255,
                validators=[rulesets.validators.validate_starting_gold_formula],
            ),
        ),
    ]
