# Generated by Django 5.2.14 on 2026-05-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
